---
# tasks file for mongoDB setup

- name: install mongoDB
  apt: 
    name: mongodb
    state: present
    update_cache: yes
  notify:
    - start mongodb

- name: copy config file
  copy:
    src: mongodb.conf
    dest: /etc/mongodb.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mongodb

- name: Ensure mongodb is running and and enabled to start automatically on reboots
  systemd:
    name: mongodb
    enabled: yes
    state: started

- name: install ntp
  apt: 
    name: ntp
    state: present
    update_cache: yes