users:
  - default
  - name: vmuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDemqkCohPk9l67RwM6MoTMqD1h53RVysk0L9kvErhY4FYukzcFuanOrc6Ijz2Qk2w8iDsWdme1j1st7SeNaVmFeekUTnE3QPXiLuVpcrWlvDtZrcTA7ZR9s6al912xF7Y5XVlVdCBZF3jQ9SvAaYBG1BiMOjzJNw6ocWulMgN9jGhOCw2N3d0oGzgs4zm1sfphSGbX9VEHQm4csRYuHqfftD1lt1W5xJvREIRocFRJu8gkvgu8nZWJScQs/3l64mw9vPMlnrYYkK7gbcNx3+HdfxknSvsbTAwmlAUNQyCLImfte3YiRrPXzMLv6sufRJCzSeBOGMHn2waPEIn4D1jfcXUNxsZmJAwSr8AfNY34s6ABGfvQ/SzfjJZfrbCkWyE/OKjLXJH6YtIYPQnglRfj7ZeMqMj5HyXwcRismY8mv1FeakW0dsv5Iu98k6lCrHwRqvPNyC52NtMphQ8v0ThWSF2cyEwCPfSJv0CERz36/YJtO5rOn/bfJn/O2Qt56+c= vmuser



