---

- name: Prerequisites
  hosts: all
  become: true
  roles:
    - common


- name: setup client service
  hosts: client
  become: true
  tags: apache
  vars:
    http_port: 8000
  roles:
    - common
    - client

- name: setup backend service
  hosts: backend
  become: true
  roles:
    - common
    - backend

- name: Setup MongoDB
  hosts: mongodb
  become: true
  roles:
    - common
    - mongodb



